install cordova 3.4.0

diff --git a/platforms/ios/cordova/run b/platforms/ios/cordova/run
--- a/platforms/ios/cordova/run
+++ b/platforms/ios/cordova/run
@@ -1,4 +1,4 @@
-#! /bin/sh
+#!/usr/bin/env bash
 #
 # Licensed to the Apache Software Foundation (ASF) under one
 # or more contributor license agreements.  See the NOTICE file
@@ -7,9 +7,9 @@
 # to you under the Apache License, Version 2.0 (the
 # "License"); you may not use this file except in compliance
 # with the License.  You may obtain a copy of the License at
-# 
+#
 # http://www.apache.org/licenses/LICENSE-2.0
-# 
+#
 # Unless required by applicable law or agreed to in writing,
 # software distributed under the License is distributed on an
 # "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
@@ -17,42 +17,143 @@
 # specific language governing permissions and limitations
 # under the License.
 #
+# Valid values for "--target" (case insensitive):
+#     "iPhone (Retina 3.5-inch)" (default)
+#     "iPhone (Retina 4-inch)"
+#     "iPhone"
+#     "iPad"
+#     "iPad (Retina)"
 
-set -e
+OPTION_RESULT=()
+TARGET="iPhone (Retina 3.5-inch)"
+TARGET_FLAG='--family iphone --retina'
+# multi-device flow default
+USE_DEVICE=true
+USE_SIMULATOR=false
 
-XCODE_VER=$(xcodebuild -version | head -n 1 | sed -e 's/Xcode //')
-XCODE_MIN_VERSION="4.5"
+# separates "key=value", sets an array with 0th index as key, 1st index as value
+_parseOption()
+{
+    local ARG=$@
+    OIFS=$IFS
+    IFS='='
 
-if [[ "$XCODE_VER" < "$XCODE_MIN_VERSION" ]]; then
-	echo "Cordova can only run in Xcode version $XCODE_MIN_VERSION or greater."
-	exit 1
-fi
+    OPTION_RESULT=()
+    for i in ${ARG[@]}
+    do
+      OPTION_RESULT+=($i)
+    done
+
+    IFS=$OIFS
+}
+
+# parses key=value arguments
+_parseArgs()
+{
+  for arg in "$@"
+  do
+    _parseOption ${arg}
+    case "${OPTION_RESULT[0]}" in
+      "--target")
+        TARGET=${OPTION_RESULT[1]}
+        ;;
+    "--device")
+      USE_DEVICE=true
+      USE_SIMULATOR=false
+      ;;
+    "--emulator")
+      USE_DEVICE=false
+      USE_SIMULATOR=true
+      ;;
+    esac
+  done
+}
+
+_parseArgs "$@"
+
+# "iPhone (Retina 3.5-inch)" -> --family iphone --retina
+# "iPhone (Retina 4-inch)" -> --family iphone --retina --tall
+# "iPhone" -> --family iphone
+# "iPad" -> --family ipad
+# "iPad (Retina)" -> --family ipad --retina
+
+# lowercase the target string
+TARGET_LC=`echo $TARGET | tr '[:upper:]' '[:lower:]'`
+
+# remember the comparison is lowercase
+case "$TARGET_LC" in
+  "iphone (retina 3.5-inch)")
+    TARGET_FLAG="--family iphone --retina"
+    ;;
+    "iphone (retina 4-inch)")
+    TARGET_FLAG="--family iphone --retina --tall"
+    ;;
+    "iphone")
+    TARGET_FLAG="--family iphone"
+    ;;
+    "ipad")
+    TARGET_FLAG="--family ipad"
+    ;;
+    "ipad (retina)")
+    TARGET_FLAG="--family ipad --retina"
+    ;;
+esac
 
 CORDOVA_PATH=$( cd "$( dirname "$0" )" && pwd -P)
 PROJECT_PATH="$(dirname "$CORDOVA_PATH")"
 XCODEPROJ=$( ls "$PROJECT_PATH" | grep .xcodeproj  )
 PROJECT_NAME=$(basename "$XCODEPROJ" .xcodeproj)
 
-APP_PATH=$1
+SIMULATOR_APP_PATH="$PROJECT_PATH/build/emulator/$PROJECT_NAME.app"
+DEVICE_APP_PATH="$PROJECT_PATH/build/device/$PROJECT_NAME.app"
 
-if [ $# -lt 1 ]; then
-	APP_PATH="$PROJECT_PATH/build/$PROJECT_NAME.app"
+source "$CORDOVA_PATH/check_reqs"
+
+
+# if device build found, run it first
+if "$USE_DEVICE"; then
+    IOS_DEPLOY_MIN_VERSION="1.0.4"
+    IOS_DEPLOY_LOCATION=$(which ios-deploy)
+    if [ $? != 0 ]; then
+        echo -e "\033[31mError: ios-deploy was not found. Please download, build and install version $IOS_DEPLOY_MIN_VERSION or greater from https://github.com/phonegap/ios-deploy into your path. Or 'npm install -g ios-deploy' using node.js: http://nodejs.org/\033[m" 1>&2;
+    	exit 1
+    fi
+
+    IOS_DEPLOY_VERSION=$(ios-deploy --version)
+    if [[ "$IOS_DEPLOY_VERSION" < "$IOS_DEPLOY_MIN_VERSION" ]]; then
+    	echo "Cordova needs ios-deploy version $IOS_DEPLOY_MIN_VERSION or greater, you have version $IOS_DEPLOY_VERSION." 1>&2;
+    	exit 1
+    fi
+    
+    DEVICE_CONNECTED=$(ios-deploy -c)
+    if [ $? != 0 ]; then
+    	echo "No device is connected, trying Simulator." 1>&2;
+        USE_SIMULATOR=true
+    else
+        # if we got here, we can deploy the app, then exit success
+        "$CORDOVA_PATH/build" --device || exit $?
+        ios-deploy -d -b "$DEVICE_APP_PATH"
+    	exit 0
+    fi
 fi
 
-if [ ! -d "$APP_PATH" ]; then
-	echo "Project '$APP_PATH' is not built. Building."
-    $CORDOVA_PATH/build || exit $?
-fi
+if "$USE_SIMULATOR"; then
+    IOS_SIM_MIN_VERSION="1.7"
+    IOS_SIM_LOCATION=$(which ios-sim)
+    if [ $? != 0 ]; then
+        echo -e "\033[31mError: ios-sim was not found. Please download, build and install version $IOS_SIM_MIN_VERSION or greater from https://github.com/phonegap/ios-sim into your path. Or 'npm install -g ios-sim' using node.js: http://nodejs.org/\033[m" 1>&2;
+    	exit 1
+    fi
 
-if [ ! -d "$APP_PATH" ]; then
-	echo "$APP_PATH not found to emulate."
-	exit 1
-fi
+    IOS_SIM_VERSION=$(ios-sim --version)
 
-# launch using ios-sim
-if which ios-sim >/dev/null; then
-    ios-sim launch "$APP_PATH" --stderr "$CORDOVA_PATH/console.log" --stdout "$CORDOVA_PATH/console.log" &
-else
-    echo -e '\033[31mError: ios-sim was not found. Please download, build and install version 1.4 or greater from https://github.com/phonegap/ios-sim into your path. Or "brew install ios-sim" using homebrew: http://mxcl.github.com/homebrew/\033[m'; exit 1;
+    if [[ "$IOS_SIM_VERSION" < "$IOS_SIM_MIN_VERSION" ]]; then
+    	echo "Cordova needs ios-sim version $IOS_SIM_MIN_VERSION or greater, you have version $IOS_SIM_VERSION." 1>&2;
+    	exit 1
+    fi
+    
+    # launch using ios-sim
+    "$CORDOVA_PATH/build" --emulator || exit $?
+    ios-sim launch "$SIMULATOR_APP_PATH" --stderr "$CORDOVA_PATH/console.log" --stdout "$CORDOVA_PATH/console.log" $TARGET_FLAG --exit
 fi
 
